import type { OpenConstructionSet } from './items.gen'

export enum ItemType {
  Building,
  Character,
  Weapon,
  Armour,
  Item,
  AnimalAnimation,
  Attachment,
  Race,
  Location,
  WarSavestate,
  Faction,
  NullItem,
  ZoneMap,
  Town,
  WorldmapCharacter,
  CharacterAppearanceOld,
  LocationalDamage,
  CombatTechnique,
  Dialogue,
  DialogueLine,
  Techtree,
  Research,
  AiTask,
  AiState,
  Animation,
  Stats,
  Personality,
  Constants,
  Biomes,
  BuildingPart,
  InstanceCollection,
  DialogAction,
  TemporaryInfo,
  ModFilename,
  Platoon,
  GamestateBuilding,
  GamestateCharacter,
  GamestateFaction,
  GamestateTownInstanceList,
  State,
  SavedState,
  InventoryState,
  InventoryItemState,
  RepeatableBuildingPartSlot,
  MaterialSpec,
  MaterialSpecsCollection,
  Container,
  MaterialSpecsClothing,
  GamestateBuildingInterior,
  VendorList,
  MaterialSpecsWeapon,
  WeaponManufacturer,
  SquadTemplate,
  Road,
  LocationNode,
  ColorData,
  Camera,
  MedicalState,
  MedicalPartState,
  FoliageLayer,
  FoliageMesh,
  Grass,
  BuildingFunctionality,
  DaySchedule,
  NewGameStartoff,
  GamestateCrafting,
  CharacterAppearance,
  GamestateAi,
  WildlifeBirds,
  MapFeatures,
  DiplomaticAssaults,
  SingleDiplomaticAssault,
  AiPackage,
  DialoguePackage,
  GunData,
  HumanCharacter,
  AnimalCharacter,
  UniqueSquadTemplate,
  FactionTemplate,
  AiSchedule,
  Weather,
  Season,
  Effect,
  ItemPlacementGroup,
  WordSwaps,
  Nest,
  NestItem,
  CharacterPhysicsAttachment,
  Light,
  Head,
  Blueprint,
  ShopTraderClass,
  FoliageBuilding,
  FactionCampaign,
  GamestateTown,
  BiomeGroup,
  EffectFogVolume,
  FarmData,
  FarmPart,
  EnvironmentResources,
  RaceGroup,
  Artifacts,
  MapItem,
  BuildingsSwap,
  ItemsCulture,
  AnimationEvent,
  Tutorial,
  Crossbow,
  TerrainDecals,
  AmbientSound,
  WorldEventState,
  LimbReplacement,
  AnimationFile,
  Boat,
  GamestateBoat,
  BuildGrid,
  BuildingShell,
  ObjectTypeMax,
}

export const GAMEDATA_ITEMS_SECTIONS: Record<OpenConstructionSet.Data.IItem.Type, string> = {
  [ItemType.Weapon]: 'Weapons',
  [ItemType.Crossbow]: 'Crossbows',
  [ItemType.Armour]: 'Armour',
  [ItemType.Container]: 'Bags',
  [ItemType.NestItem]: 'Nest Items',
  [ItemType.MapItem]: 'Maps',
  [ItemType.LimbReplacement]: 'Limb Replacements',
  [ItemType.Item]: 'Other',
}

export const GAMEDATA_ITEMS_SECTIONS_LIST: ItemType[] = [
  ItemType.Weapon,
  ItemType.Crossbow,
  ItemType.Armour,
  ItemType.Container,
  ItemType.NestItem,
  ItemType.MapItem,
  ItemType.LimbReplacement,
  ItemType.Item,
]
